# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: HSG Networks - Homepage
description: 
baseurl: / # the subpath of your site, e.g. /support
url: https://hsgnetworks.com # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

#content_type: #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo_transparent.png
brand_name: HSG Networks
header: How can we help you?
subheader: Providing Innovative Solutions!

meta_image: odin-meta.png

# Social Links
twitter_username: #
facebook_page:
github_username: #
email: contact@hsgnetworks.com
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://hsgnetworks.com/

nav_item_two: Twitter
nav_item_two_link: https://hsgnetworks.com/

nav_item_three: #
nav_item_three_link: #

nav_button: Return to Home
nav_button_link: https://hsgnetworks.com/

# More Help
help_one_title: Call Us
help_one_content: If you want to disclose any security vulnerability, please email our security team.
help_one_button: Security
help_one_link: mailto:psirt@hsgnetworks.com

help_two_title: Reach Us
help_two_content: Feel free to call or email us even if you just want to say hi.
help_two_button: Reach Us
help_two_link: mailto:contact@hsgnetworks.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
