#This file defines all the categories you are using


automation:
  name: E-Commerce Platform
  description: Innovate E-commerce Solutions for small and medium business.
security:
  name: Security
  description: Security Services Provided by Us!
contactus:
  name: Contact Us
  description: Say Hello!
#customizing-odin:
#  name: Customizing Odin
#  description: Welcome to Odin, time to get started
