#This file defines all the categories you are using


automation:
  name: Custom Automation
  description: Tired of doing same things? Let us Automate.
security:
  name: Security
  description: Security Services Provided by Us!
contactus:
  name: Contact Us
  description: Say Hello!
#customizing-odin:
#  name: Customizing Odin
#  description: Welcome to Odin, time to get started
